# Generated by Django 3.0.dev20190326171141 on 2019-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(upload_to='pictures/static/pictures/pix/'),
        ),
    ]
