# Generated by Django 3.0.dev20190326171141 on 2019-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20190327_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='upload_time',
        ),
        migrations.AlterField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(upload_to='pictures/static/pictures/pix'),
        ),
    ]
