# Generated by Django 3.0.dev20190326171141 on 2019-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20190327_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(default=str, null=bool, upload_to='pictures/static/pictures/pix'),
        ),
    ]
